"""
Bicep template generator for AKS Arc deployments
"""

from typing import Dict
from src.models import DeploymentPlan


class BicepGenerator:
    """Generate Bicep templates for AKS Arc clusters"""
    
    def generate(self, plan: DeploymentPlan) -> str:
        """
        Generate a Bicep template from deployment plan.
        
        Args:
            plan: Deployment plan with cluster configuration
            
        Returns:
            Bicep template as string
        """
        cluster = plan.cluster_config
        
        # TODO: Use Azure Verified Modules for AKS
        template = f"""// AKS Arc Cluster Deployment
// Generated by AKS Arc Deployment Tool

targetScope = 'resourceGroup'

@description('Name of the AKS Arc cluster')
param clusterName string = '{cluster.cluster_name}'

@description('Azure region')
param location string = '{cluster.location}'

@description('Kubernetes version')
param kubernetesVersion string = '{cluster.kubernetes_version}'

@description('Control plane node count')
param controlPlaneCount int = {cluster.control_plane_count}

// TODO: Add Arc custom location reference
// TODO: Add node pool configurations
// TODO: Add rack-awareness labels and constraints

resource aksCluster 'Microsoft.Kubernetes/connectedClusters@2024-01-01' = {{
  name: clusterName
  location: location
  properties: {{
    agentPublicKeyCertificate: ''
    // Additional properties for Azure Arc-enabled Kubernetes
  }}
}}

// Node pools
"""
        
        for i, pool in enumerate(cluster.node_pools):
            template += f"""
resource nodePool{i} 'Microsoft.ContainerService/managedClusters/agentPools@2024-01-01' = {{
  name: '{pool.name}'
  properties: {{
    count: {pool.node_count}
    vmSize: '{pool.vm_size}'
    osType: '{pool.os_type.value.capitalize()}'
    mode: '{"System" if i == 0 else "User"}'
    enableAutoScaling: {str(pool.enable_auto_scaling).lower()}
    minCount: {pool.min_count if pool.min_count else pool.node_count}
    maxCount: {pool.max_count if pool.max_count else pool.node_count}
    maxPods: {pool.max_pods}
    nodeLabels: {{
"""
            for key, value in pool.labels.items():
                template += f"      '{key}': '{value}'\n"
            template += "    }\n"
            
            if pool.taints:
                template += "    nodeTaints: [\n"
                for taint in pool.taints:
                    template += f"      '{taint}'\n"
                template += "    ]\n"
            
            template += "  }\n}\n"
        
        template += """
output clusterName string = aksCluster.name
output clusterId string = aksCluster.id
"""
        
        return template
