"""
Terraform generator for AKS Arc deployments using AzAPI provider
"""

from typing import Dict
from src.models import DeploymentPlan


class TerraformGenerator:
    """Generate Terraform configurations for AKS Arc clusters"""
    
    def generate(self, plan: DeploymentPlan) -> str:
        """
        Generate a Terraform configuration from deployment plan.
        
        Args:
            plan: Deployment plan with cluster configuration
            
        Returns:
            Terraform configuration as string
        """
        cluster = plan.cluster_config
        
        template = f"""# AKS Arc Cluster Deployment
# Generated by AKS Arc Deployment Tool

terraform {{
  required_version = ">= 1.6"
  
  required_providers {{
    azapi = {{
      source  = "Azure/azapi"
      version = "~> 1.12"
    }}
    azurerm = {{
      source  = "hashicorp/azurerm"
      version = "~> 3.80"
    }}
  }}
}}

provider "azurerm" {{
  features {{}}
}}

provider "azapi" {{}}

variable "cluster_name" {{
  type        = string
  default     = "{cluster.cluster_name}"
  description = "Name of the AKS Arc cluster"
}}

variable "resource_group" {{
  type        = string
  default     = "{cluster.resource_group}"
  description = "Resource group name"
}}

variable "location" {{
  type        = string
  default     = "{cluster.location}"
  description = "Azure region"
}}

variable "kubernetes_version" {{
  type        = string
  default     = "{cluster.kubernetes_version}"
  description = "Kubernetes version"
}}

# Azure Arc-enabled Kubernetes Cluster
resource "azapi_resource" "aks_arc_cluster" {{
  type      = "Microsoft.Kubernetes/connectedClusters@2024-01-01"
  name      = var.cluster_name
  parent_id = "/subscriptions/${{data.azurerm_subscription.current.subscription_id}}/resourceGroups/${{var.resource_group}}"
  location  = var.location
  
  body = jsonencode({{
    properties = {{
      agentPublicKeyCertificate = ""
      # Additional Arc-specific properties
    }}
  }})
}}

data "azurerm_subscription" "current" {{}}

"""
        
        # Add node pools
        for i, pool in enumerate(cluster.node_pools):
            template += f"""
# Node Pool: {pool.name}
resource "azapi_resource" "nodepool_{pool.name}" {{
  type      = "Microsoft.ContainerService/managedClusters/agentPools@2024-01-01"
  name      = "{pool.name}"
  parent_id = azapi_resource.aks_arc_cluster.id
  
  body = jsonencode({{
    properties = {{
      count             = {pool.node_count}
      vmSize            = "{pool.vm_size}"
      osType            = "{pool.os_type.value.capitalize()}"
      mode              = "{"System" if i == 0 else "User"}"
      enableAutoScaling = {str(pool.enable_auto_scaling).lower()}
      minCount          = {pool.min_count if pool.min_count else pool.node_count}
      maxCount          = {pool.max_count if pool.max_count else pool.node_count}
      maxPods           = {pool.max_pods}
      nodeLabels = {{
"""
            for key, value in pool.labels.items():
                template += f'        "{key}" = "{value}"\n'
            template += "      }\n"
            
            if pool.taints:
                template += "      nodeTaints = [\n"
                for taint in pool.taints:
                    template += f'        "{taint}",\n'
                template += "      ]\n"
            
            template += "    }\n  })\n}\n"
        
        template += """
output "cluster_name" {
  value       = azapi_resource.aks_arc_cluster.name
  description = "The name of the AKS Arc cluster"
}

output "cluster_id" {
  value       = azapi_resource.aks_arc_cluster.id
  description = "The resource ID of the AKS Arc cluster"
}
"""
        
        return template
